services:
  planet-simulation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: planet-simulation
    ports:
      - "${APP_PORT:-8080}:80"
    restart: unless-stopped
    networks:
      - npm_network

networks:
  npm_network:
    name: ${NPM_NETWORK_NAME:-bridge}
    external: true
